theme: jekyll-theme-minimal
logo: ./doc/me.jpeg
title: Yejing Wang's HomePage
description: Thanks for visiting my homepage and welcome to contact me at:<br /><br /><a href="mailto:adave631@gmail.com">📮 adave631@gmail.com</a><br />
